# ---- Include directory for this folder ----
exchange_inc = include_directories('.')

# ---- Header-only exchange boundary / simulator ----
exchange_sources = files(
    'exchange_event.h',
    'exchange.h',
    'message_bus_exchange.cpp',
    'nats_backend_exchange_gateway_adapter.cpp',
    'simulated_exchange.h'
)
