# ---- Include directory for this folder ----
runtime_inc = include_directories('.')

# ---- Source files ----
runtime_sources = files(
    'decision_engine.cpp',
    'execution_engine.cpp',
    'execution_planning_state.cpp',
    'order_planner_engine.cpp',
    'portfolio_risk_engine.cpp',
    'rolling_market_state.cpp',
    'strategy_signal_engine.cpp',
    'trading_engine.cpp'
)
